### ISSUE TITLE
Task stage wise team member allocation

### ISSUE THREAD

**Issue by shwecchajain** [madrecha/jamku#19]
## Problem
Currently, team members can only be added to a Task. There is no way to assign a team member to a particular Task Stage.

## Feature
Task stage wise team member allocation

**Comment by TulikaKhetan** [comment]
This is a useful feature. In certain services, different stages are done by different team member. 
So instead of adding all the team members to the task or creating a sub task for all such activities, it would be easier if a team member could be linked to/ assigned to a specific stage in a task.
This can help both the team leader and a team member to ascertain when is his role in a specific task.

**Comment by adarshmadrecha** [comment]
This feature request was created way back in 2019. Now that we have Todo feature, we won't be bringing this, hence closing this issue.
