### ISSUE TITLE
Billing at Client Level

### ISSUE THREAD

**Issue by yogeshkudikala** [madrecha/jamku#429]
To create bills at client level

**Comment by vatsalbhatia** [comment]
highly needed along with bill location at client level
plus option be allowed from task costing page to select multiple tasks and to bill those in a specific bill (new bill) directly

**Comment by vatsalbhatia** [comment]
pl refer #343

**Comment by vatsalbhatia** [comment]
Similarly there should be an option to bill a task if we are task view page, saying, bill this task....

**Comment by cadev71** [comment]
There should be a system to bill client wise - task wise if required- while selecting a particular group for bill. I am attaching
[1.pdf](https://github.com/adarshmadrecha/jamku/files/6254349/1.pdf)
 a file for refence

**Comment by vatsalbhatia** [comment]
Screenshot should be considered at highest priority, already a user of this feature there.

**Comment by cadev71** [comment]
Billing process should be made in such a way that can help Practicing firms in proper time without much efforts.....Billing to client on time and collection with proper due statement is a must requirement in this compliance presser and due dates.....billing group wise but to the client in the group at at time for each task provided to the clients in the period....regular billing for recurring work and same amount each month to be made automatically....due list groupwise and client wise as required.......Billing is the must compliance for every practicing firm and timely billing will reduce revenue linkage.....jamku team should consider this also in priority since client management is not possible without proper system of billing and collection.

**Comment by adarshmadrecha** [comment]
> There should be a system to bill client wise - task wise if required- while selecting a particular group for bill. I am attaching [1.pdf](https://github.com/adarshmadrecha/jamku/files/6254349/1.pdf) a file for refence

@cadev71 Now this is possible using Bulk Billing Functionality in Task List and Task Costing Page.

**Comment by adarshmadrecha** [comment]
Now (v3.29.0) we have option to create Bill at Client Level.
https://help.jamku.app/changes/202205.html#_3-29-0
