### ISSUE TITLE
Better Task List Filters and Other Small Improvements

### ISSUE THREAD

**Issue by capostwal** [madrecha/jamku#860]
### Feature Request

In Task List (Table- Edit mode )
1. In Task list whenever any field is edited, after refresh it goes to first page /record instead of staying on a row which is edited. so every time whenever we change any details of particular task, it goes to first task row and we have to scroll it down to the task again.
2. In Date Fields if date picker is provided the it will be more convenient because putting a date in a specific format is sometimes difficult.
3. Filter - In a Task Name, filter should allow to select multiple Items( Like Filter present inf Teams field). Currently we have to Put task Name containing ...... sometimes it is difficult while filtering multiple task.
![image](https://user-images.githubusercontent.com/79853108/146626182-f486a6e7-8b96-485d-8f8a-c642f2a5ed42.png)

**Comment by adarshmadrecha** [comment]
@capostwal PFB my comments

> 1. In Task list whenever any field is edited, after refresh it goes to first page /record instead of staying on a row which is edited. so every time whenever we change any details of particular task, it goes to first task row and we have to scroll it down to the task again.

Will check if there is option to do Incremental Update. So that state of filter and position is maintained.
We are using an external library to power the Table View. Hence we are limited by the functionality it provides.

<br/>

> 2. In Date Fields if date picker is provided the it will be more convenient because putting a date in a specific format is sometimes difficult.

Giving date picker will limit the possibility of filtering. Example: If you wish to filter tasks which are due in December 2021, you can enter `2021-12`. If the date picker is provided, this functionality will be lost.

<br/>

> 3. Filter - In a Task Name, filter should allow to select multiple Items( Like Filter present inf Teams field). Currently we have to Put task Name containing ...... sometimes it is difficult while filtering multiple task.

The Team Filter it's possible to show list of team members as we know beforehand the list options. In case of Task Names, it's endless. If we try to provide this option in task name, we will have to scan through entire database of Task and find unique names, which shall slow down the task searching. 
_FYI, this is the reason Excel only shows 1000 unique items in Filter_

**Comment by adarshmadrecha** [comment]
## Development Note
When one filed is updated, preserve the State in Task List (Table view) (Edit Mode)

**Comment by yogeshkudikala** [comment]
It will be fixed after 
https://github.com/ag-grid/ag-grid/issues/4812#issuecomment-1003522473
